"""Write configs/paths.yaml from command-line arguments."""
# Role: writes configs/paths.yaml, which cuhkx.paths reads: the test folder, the sample
#   submission, and the folders for the caches and the intermediate tables.
# Used by: run_inference.sh; inference.
import argparse
from pathlib import Path

# Package root and the path file that cuhkx.paths reads.
ROOT = Path(__file__).resolve().parents[1]
CONFIG = ROOT / "configs" / "paths.yaml"


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--data_dir", required=True,
                    help="Directory containing the SM_test_XXXX clip folders.")
    ap.add_argument("--sample_submission", required=True,
                    help="Official sample_submission.csv (columns: path,prediction).")
    ap.add_argument("--cache_root", default="outputs/cache")
    ap.add_argument("--processed_root", default="outputs/processed")
    a = ap.parse_args()

    # Resolve both inputs to absolute paths; the folder must directly hold SM_test_* clip folders
    # and the sample submission must be a file.
    data_dir = Path(a.data_dir).expanduser().resolve()
    sample = Path(a.sample_submission).expanduser().resolve()
    if not data_dir.is_dir():
        raise SystemExit(f"--data_dir is not a directory: {data_dir}")
    clips = sorted(c for c in data_dir.glob("SM_test_*") if c.is_dir())
    if not clips:
        raise SystemExit(
            f"No SM_test_* clip folders directly under {data_dir}. "
            "Point --data_dir at the folder that contains them."
        )
    if not sample.is_file():
        raise SystemExit(f"--sample_submission is not a file: {sample}")

    # Values are written with repr(), i.e. as quoted strings; cache_root and processed_root are
    # written as given (relative by default). train_root is a placeholder: inference reads no
    # training data.
    CONFIG.write_text(
        "# Generated by tools/configure_paths.py -- do not edit by hand.\n"
        "# Relative values resolve against the package root (inference.sh cds there).\n"
        f"test_root: {str(data_dir)!r}\n"
        f"sample_submission: {str(sample)!r}\n"
        f"cache_root: {a.cache_root!r}\n"
        f"processed_root: {a.processed_root!r}\n"
        "train_root: 'UNUSED_AT_INFERENCE'\n",
        encoding="utf-8",
    )
    print(f"wrote {CONFIG}")
    print(f"  test_root         = {data_dir}  ({len(clips)} clip folders)")
    print(f"  sample_submission = {sample}")
    print(f"  cache_root        = {a.cache_root}")
    print(f"  processed_root    = {a.processed_root}")


if __name__ == "__main__":
    main()
